name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       dockerfile: [./test/Dockerfile, ./prod/Dockerfile]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.dockerfile }} --tag my-image-name:$(date +%s)
