name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       dockerfile: [test/Dockerfile, prod/Dockerfile]

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        file: ${{ matrix.dockerfile }}
            