name: container-test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - environment: 'container-test'
            dockerfile: 'test/Dockerfile'

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        file: ${{ matrix.dockerfile }}
        tags: ${{ matrix.environment }}
